on: [repository_dispatch]
name: Build agent on multiple rust versions
jobs:
  build_nightly:
    name: Nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            target: x86_64-unknown-linux-musl
            override: true
      - name: Environmental preparation
        run: |
          sudo apt-get install musl-tools
      - name: Make
        working-directory: ./src/agent
        run: make
  build_stable:
    name: Stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: x86_64-unknown-linux-musl
            override: true
      - name: Environmental preparation
        run: |
          sudo apt-get install musl-tools
      - name: Make
        working-directory: ./src/agent
        run: make
