on:
  repository_dispatch:
    types: [build-agent-multi]
name: Build agent on multiple rust versions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/bam'
          prefix_only: true
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
  build_nightly:
    if: steps.check.outputs.triggered == 'true'
    name: Nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            target: x86_64-unknown-linux-musl
            override: true
      - name: Environmental preparation
        run: |
          sudo apt-get install musl-tools
      - name: Make
        working-directory: ./src/agent
        run: make
  build_stable:
    name: Stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: x86_64-unknown-linux-musl
            override: true
      - name: Environmental preparation
        run: |
          sudo apt-get install musl-tools
      - name: Make
        working-directory: ./src/agent
        run: make
